### ISSUE TITLE
Add OS info

### ISSUE THREAD

**Issue by aadshalshihry** [tagable/eight-pro#2]
Add OS info module

## Todo

- [ ] Return the Mac info
- [ ] Return the Linux info
- [ ] Return the Win info
